### ISSUE TITLE
Updating items 

### ISSUE THREAD

**Issue by ioverka** [imeji-community/pyimeji#18]
Hi,

this is rather a question than an "issue". It looks like updating existing items (PUT requests to /items/{id}) is supported by the pyimeji wrapper - and I would like to submit a new file 

The api.patch() mentioned in the tutorial doesn't seem to exist any longer?

    from pyimeji.api import Imeji
    api = Imeji()
    id = "ciEByHKQ_5LT1Obq"
    item = api.item(id)
    api.patch(item, metadata = {"Title" : "TestTitle"})

Traceback (most recent call last): [...] AttributeError: 'module' object has no attribute 'Patch'

Alternatively, I tried to request an item, manipulate it locally and save it:

    item.metadata[0]["value"]["text"] = "hasihasi"
    item.save()

... but this returns an error from the API:

    DEBUG:requests.packages.urllib3.connectionpool:"PUT //rest/items/ciEByHKQ_5LT1Obq 
    ERROR:pyimeji.api:got HTTP 422, expected HTTP 200
    ERROR:pyimeji.api:{u'error': {u'message': u'1422-message', u'code': u'1422', u'exceptionReport': u'Same file already exists in the collection or you are trying to upload same file for the item (with same checksum). Please choose another file.', u'title': u'Unprocessable Entity'}}

Am I just overlooking something obvious? Both of the above scenarios also seem to be restricted to updating the metadata - and I want to submit a new version of the actual file. 

Note: I managed to do it via https://spot.mpdl.mpg.de/rest-doc/index.html#!/items/update

Note 2: It's not so important, updating files is the exception rather than the rule - it's no problem to delete and readd.

cheers,
inga

**Comment by xrotwang** [comment]
I think the using the PATCH method was exactly meant to address your use case of manipulating only the metadata of an item. But [AFAIK](https://dev-faces.mpdl.mpg.de/rest-doc/index.html#!/items) this is not implemented by imeji, because the envisioned condensed metadata format didn't work out (see the discussions [here](https://github.com/MPDL-Innovations/spot/issues/231)).

From my point of view, this should be considered an imeji bug; I think it should simply accept - i.e. ignore - the identical file.

**Comment by ioverka** [comment]
Okay, current status is:
* the patch method has been removed from api.py and is no longer mentioned in the tutorial
* item.save() works even if only metadata has been modified

So, I guess the issue can be closed
